### ISSUE TITLE
Using chose-method default - Ivy and https

### ISSUE THREAD

**Issue by technician77** [hpdeifel/synosaurus#10]
I would like to use ivy in combination with synosaurus, but when I select chose-method default I get:

```
Contacting host: www.openthesaurus.de:80
ivy--reset-state: Invalid function: ("Erprobung" "Probe" "Prüfung" "Test" "Versuch" "Muster" "Warenmuster" "Training" "Übung")
```
Additionally I've seen that it uses Port 80. Why not https (443)?

**Comment by hpdeifel** [comment]
> I would like to use ivy in combination with synosaurus, but when I select chose-method default I get:
> 
> ```
> Contacting host: www.openthesaurus.de:80
> ivy--reset-state: Invalid function: ("Erprobung" "Probe" "Prüfung" "Test" "Versuch" "Muster" "Warenmuster" "Training" "Übung")
> ```

It works for me when setting `choose-method` to `default`.

> Additionally I've seen that it uses Port 80. Why not https (443)?

Oversight :frowning_face:. PR welcome

**Comment by technician77** [comment]
You might try for error-fun:
(setq ivy-completing-read-dynamic-collection t)
I'm not a programmer, I better not fiddle with source-code.

**Comment by hpdeifel** [comment]
The http URL is now fixed in 7c8945b184b67caf8eae7f336f76827f0ab9d998

**Comment by hpdeifel** [comment]
@technician77 is `ivy-completing-read-dynamic-collection` even a variable that should be set globally by the user? It looks like it's just for very specific use cases and should only set to `t` inside `let`

**Comment by technician77** [comment]
I guess you are right.
