### ISSUE TITLE
what is the key binding to turn the pop up off?

### ISSUE THREAD

**Issue by yilihong** [hpdeifel/synosaurus#3]
It appears I can't turn the pop up off using ESC or any conventional keys. Any ideas?

**Comment by hpdeifel** [comment]
> It appears I can't turn the pop up off using ESC or any conventional
> keys. Any ideas?

C-g works, which is kind of conventional for emacs. This comes from the
popup.el library, which only binds C-g.

I'll see if I can do something about it.

**Comment by yilihong** [comment]
Thanks for the quick reply! It works with C-g.

Kevin

On Aug 12, 2016, at 3:39 AM, Hans-Peter Deifel <notifications@github.com<mailto:notifications@github.com>> wrote:

> It appears I can't turn the pop up off using ESC or any conventional
> keys. Any ideas?

C-g works, which is kind of conventional for emacs. This comes from the
popup.el library, which only binds C-g.

I'll see if I can do something about it.

**Comment by hpdeifel** [comment]
I thought about adding a custom keymap that binds escape or something
similar. But the way popup.el's keymaps work, this would require more
complication than I'd like for such a simple feature.

So I think C-g is fine for now. If more users feel that escape should
work, I might reconsider.
