### ISSUE TITLE
synosaurus-lookup only uses WordNet

### ISSUE THREAD

**Issue by timmli** [hpdeifel/synosaurus#4]
I told synosaurus to use OpenThesaurus with `(setq synosaurus-backend 'synosaurus-backend-openthesaurus)`. However, when using `synsaurus-lookup`, the following error message is shown: 
> Searching for program: No such file or directory, wn

Obviously, it still tries to use WordNet, which is not installed on my machine. 

No problems with `synosaurus-choose-and-replace`.

**Comment by theldoria** [comment]
I was surprised by this dependency. It's not mentiond in the readme, but one should know that.

**Comment by hpdeifel** [comment]
I can reproduce that. The problem seems to be that the global binding of the variable `synosaurus-backend` is used for backend selection instead of the local one. I will look into that.

In the meantime, you can set the backend globally (as opposed to buffer-local) with:

    (setq-default synosaurus-backend 'synosaurus-backend-openthesaurus)

**Comment by hpdeifel** [comment]
Should be fixed now, but #5 still remains

**Comment by hpdeifel** [comment]
And #5 is fixed. Everything should work now

**Comment by timmli** [comment]
It works for me. Thanks!
