### ISSUE TITLE
Default key bindings block keys reserved for users

### ISSUE THREAD

**Issue by tie-rack** [hpdeifel/synosaurus#6]
From the Emacs manual section, [Key Binding Conventions](https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html):

> Don't define `C-c` _letter_ as a key in Lisp programs. Sequences consisting of `C-c` and a letter (either upper or lower case) are reserved for users; they are the **only** sequences reserved for users, so do not block them.
>
> Changing all the Emacs major modes to respect this convention was a lot of work; abandoning this convention would make that work go to waste, and inconvenience users. Please comply with it.

New keys should be chosen.

**Comment by hpdeifel** [comment]
Yeah, you're right. I could change it to <kbd>C-c C-s</kbd> or leave it unbound and let the user decide. What would you prefer?
