### ISSUE TITLE
what if the arg is provided interactivelly rather that by region or word at point?

### ISSUE THREAD

**Issue by touxstone** [hpdeifel/synosaurus#8]
https://github.com/hpdeifel/synosaurus/blob/8bf95b935976ec0a1964cf175ed57cc5f6f93bdb/synosaurus.el#L186
The reference cited above includes the case of giving the arg by higlighting the word `use-region-p = t` or in a `word-at-point = t` case but what if the arg is just passed interactivelly in the minibuffer?. What I found is that it is not inserted and outputing just `not word here`.
Any help on this? I'd appreciate it

**Comment by hpdeifel** [comment]
Thanks for the report!

I assume you're proposing that `synosaurus-choose-and-replace` does something
useful even if there's no word under point and the region is not active.

Could you please describe exactly what you are doing, which results you see
currently and what you expect the outcome to be?

**Comment by touxstone** [comment]
Well, I think I got it by adding the following to [synosaurus.el#L188](https://github.com/hpdeifel/synosaurus/blob/8bf95b935976ec0a1964cf175ed57cc5f6f93bdb/synosaurus.el#L188)
```elisp
(if (word-at-point)
    (delete-region
     (beginning-of-thing 'word) (end-of-thing 'word))
  nil)
```
So, when looking up for a word but have not highlighted anything, not a `word-at-point`, neither, or just change mind on the flight and type it in the interactive mini-buffer prompt it's called with the given `function kbd-shortcut`. (Now) You still could insert the chosen synonym `'res' in the script`

**Comment by hpdeifel** [comment]
There is now a new command `synosaurus-choose-and-insert` that works without word at point or active region. I'd like to keep the current behavior of `synosaurus-choose-and-replace` and I've made the error message if no word is at point more clear and upfront.

The long term solution to this would be to have an `ivy` or `helm` frontend with different actions for lookup, replace and insert.
